### ISSUE TITLE
TitlePage: add option for custom content

### ISSUE THREAD

**Issue by PucherSamuel** [DannySeidel/typst-dhbw-template#12]
### Problem
It is not possible to have a custom titlepage.

### Solution
For example, for the confidentiality statement it is possible to pass custom content to the `confidentiality-statement-content` option.
It would be nice, if that was possible for the titlepage as well

**Comment by DannySeidel** [comment]
Hi there,

thanks for the suggestion 🙏🏻
I will add that with the next version 🔥
