### ISSUE TITLE
Confidentiality Statement: Typo

### ISSUE THREAD

**Issue by gungula** [DannySeidel/typst-dhbw-template#13]
Typo in German version of CONFIDENTIALITY_STATEMENT_SECTION_C ("**im** Studiengang"):

> `#let CONFIDENTIALITY_STATEMENT_SECTION_C = (
> "de": ", ist deshalb mit einem Sperrvermerk versehen und wird ausschließlich zu Prüfungszwecken am Studiengang",`

locale.typ, ll. 64

**Comment by DannySeidel** [comment]
Thanks for pointing it out 🙏🏻

I will fix it with the next version 🔥
