### ISSUE TITLE
add CI pipeline for checks

### ISSUE THREAD

**Issue by Servostar** [DannySeidel/typst-dhbw-template#9]
## Motivation

Maybe having a small CI pipeline to check whether the changes from a PR or commit still allows for successful compilation of the template. This would help to avoid breaking the template, which has happened to my personal templates multiple times.

## Requirements

This would require an action file initializing Typst and compiling the template.
Additionally, the import of the library would need to be changed from the Typst `preview/supercharged-dhbw` to `../lib.typ`.
Since this invalidates the template the creation of a test document in a testes folder would be be better option.

A similar pipeline can be found here: [Typst-CI](https://github.com/Servostar/dhbw-abb-typst-template/blob/main/.github/workflows/ci.yml)

**Comment by DannySeidel** [comment]
Thanks for the suggestion, but as I already described in your PR, this repo is only a copy of the current version in typst/packages. All contributions are made in the typst/packages repo and therefore I will not add a pipeline to this repo.
